services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${PATH_OLLAMA_LOCAL}
    command: ["serve"]
    networks:
      - net

  front:
    build:
      context: front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    restart: always
    command: sh -c "npm install && npm start"
    networks:
      - net

volumes:
  ollama-local:

networks:
  net:
    external: false
