services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/tables:/docker-entrypoint-initdb.d
    networks:
      - net
  
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-local:${PATH_OLLAMA_LOCAL}
    command: ["serve"]
    networks:
      - net

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - ollama
    networks:
      - net    

  front:
    build:
      context: front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    restart: always
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
    networks:
      - net

volumes:
  ollama-local:
  postgres_storage:

networks:
  net:
    external: false
